monitor_settings = [
    '# Settings generated by the Spidermon CLI',
    'SPIDERMON_ENABLED = True',
    'EXTENSIONS = { \'spidermon.contrib.scrapy.extensions.Spidermon\': 500, }',
    'SPIDERMON_SPIDER_CLOSE_MONITORS = (\'tutorial.monitors.SpiderCloseMonitorSuite\',)',
]
