monitor_settings = [
    '\n\n# Settings generated by the Spidermon CLI\n',
    'SPIDERMON_ENABLED = True\n',
    'EXTENSIONS = { \'spidermon.contrib.scrapy.extensions.Spidermon\': 500, }\n',
    'SPIDERMON_SPIDER_CLOSE_MONITORS = (\'tutorial.monitors.SpiderCloseMonitorSuite\',)\n',
]
