TEST_STATUS_SUCCESS = 'OK'
TEST_STATUS_ERROR = 'ERROR'
TEST_STATUS_FAILURE = 'FAIL'
TEST_STATUS_SKIPPED = 'SKIPPED'
TEST_STATUS_EXPECTED_FAILURE = 'EXPECTED FAILURE'
TEST_STATUS_UNEXPECTED_SUCCESS = 'UNEXPECTED SUCCESS'

TEST_STATUSES = (
    TEST_STATUS_SUCCESS,
    TEST_STATUS_ERROR,
    TEST_STATUS_FAILURE,
    TEST_STATUS_SKIPPED,
    TEST_STATUS_EXPECTED_FAILURE,
    TEST_STATUS_UNEXPECTED_SUCCESS,
)