# ----------------------------------
# Status
# ----------------------------------
UNDEFINED_STATUS = '?'

# ----------------------------------
# Test status
# ----------------------------------
TEST_STATUS_SUCCESS = 'OK'
TEST_STATUS_ERROR = 'ERROR'
TEST_STATUS_FAILURE = 'FAIL'
TEST_STATUS_SKIPPED = 'SKIPPED'
TEST_STATUS_EXPECTED_FAILURE = 'EXPECTED FAILURE'
TEST_STATUS_UNEXPECTED_SUCCESS = 'UNEXPECTED SUCCESS'

TESTS_STATUSES = (
    TEST_STATUS_SUCCESS,
    TEST_STATUS_FAILURE,
    TEST_STATUS_ERROR,
    TEST_STATUS_SKIPPED,
    TEST_STATUS_EXPECTED_FAILURE,
    TEST_STATUS_UNEXPECTED_SUCCESS,
)
TESTS_SUCCESSFUL_STATUSES = (
    TEST_STATUS_SUCCESS,
    TEST_STATUS_SKIPPED,
    TEST_STATUS_EXPECTED_FAILURE,
    TEST_STATUS_UNEXPECTED_SUCCESS,
)
TESTS_ERROR_STATUSES = (
    TEST_STATUS_FAILURE,
    TEST_STATUS_ERROR,
)
# ----------------------------------
# Monitor Levels
# ----------------------------------
MONITOR_LEVEL_HIGH = 'HIGH'
MONITOR_LEVEL_NORMAL = 'NORMAL'
MONITOR_LEVEL_LOW = 'LOW'

MONITOR_LEVELS = (
    MONITOR_LEVEL_HIGH,
    MONITOR_LEVEL_NORMAL,
    MONITOR_LEVEL_LOW,
)

DEFAULT_MONITOR_LEVEL = MONITOR_LEVEL_NORMAL

DEFAULT_DESCRIPTION = ''
DEFAULT_ORDER = 1

# ----------------------------------
# Action status
# ----------------------------------
ACTION_STATUS_SUCCESS = 'OK'
ACTION_STATUS_ERROR = 'ERROR'
ACTION_STATUS_SKIPPED = 'SKIPPED'

ACTIONS_STATUSES = (
    ACTION_STATUS_SUCCESS,
    ACTION_STATUS_ERROR,
    ACTION_STATUS_SKIPPED,
)
ACTIONS_SUCCESSFUL_STATUSES = (
    ACTION_STATUS_SUCCESS,
    ACTION_STATUS_SKIPPED,
)
ACTIONS_ERROR_STATUSES = (
    ACTION_STATUS_ERROR,
)

# ----------------------------------
# Result steps
# ----------------------------------
STEP_TESTS = 'TESTS'
STEP_FINISH_ACTIONS = 'FINISH ACTIONS'
STEP_PASS_ACTIONS = 'PASS ACTIONS'
STEP_FAIL_ACTIONS = 'FAIL ACTIONS'

STEPS = [STEP_TESTS, STEP_FINISH_ACTIONS, STEP_PASS_ACTIONS, STEP_FAIL_ACTIONS]
TESTS_STEPS = [STEP_TESTS]
ACTIONS_STEPS = [STEP_FINISH_ACTIONS, STEP_PASS_ACTIONS, STEP_FAIL_ACTIONS]
