from importlib import import_module
from os.path import abspath, dirname, join
from scrapy.utils.project import get_project_settings

MONITOR_SETTINGS = [
    '# Settings generated by the Spidermon CLI',
    'SPIDERMON_ENABLED = True',
    'EXTENSIONS = { \'spidermon.contrib.scrapy.extensions.Spidermon\': 500, }',
    'SPIDERMON_SPIDER_CLOSE_MONITORS = (\'tutorial.monitors.SpiderCloseMonitorSuite\',)',
]

def build_monitors_strings(monitors):
    monitors_list = '['
    monitors_import = ''
    for monitor in monitors:
        monitors_list += monitor + ','
        monitors_import += 'from {} import {}\n'.format(
            monitors[monitor],
            monitor
        )
    monitors_list += ']'

    return monitors_list, monitors_import

def find_monitors():
    return [{
        'path': 'spidermon.contrib.scrapy.monitors',
        'monitors': {
            'ItemCountMonitor': 'Item Count Monitor',
            'ErrorCountMonitor': 'Error Count Monitor',
            'FinishReasonMonitor': 'Finish Reason Monitor',
            'UnwantedHTTPCodesMonitor': 'Unwanted HTTP Code Monitor',
        }
    }]

def check_settings(settings_path):
    with open(settings_path, 'r') as f:
        read_data = f.read()

        # check if spidermon was already enabled
        for setting in MONITOR_SETTINGS:
            if setting in read_data:
                return False

    return True

def include_settings(settings_path):
    with open(settings_path, 'a') as f:
        f.writelines('\n'.join(MONITOR_SETTINGS))
